/**
 * Documentation Templates
 *
 * Markdown templates for auto-generated documentation
 */

export const WORK_SUMMARY_TEMPLATE = `# Work Summary

## Execution Details
- **Project:** {{projectName}}
- **Session ID:** {{sessionId}}
- **Started:** {{startedAt}}
- **Completed:** {{completedAt}}
- **Duration:** {{duration}}
- **Mode:** {{mode}}

## Results Summary
- **Total Packets:** {{packetCount}}
- **Successful:** {{successCount}}
- **Failed:** {{failedCount}}

## Packets Processed
{{packetsTable}}

## Activity Timeline
{{activityTimeline}}

## Quality Gate Results
{{qualityGates}}

## Notes
{{notes}}

---
*Auto-generated by Claudia Coder*
`

export const USER_GUIDE_TEMPLATE = `# {{projectName}} - User Guide

## Overview
{{overview}}

## Features
{{features}}

## Getting Started

### Prerequisites
{{prerequisites}}

### Installation
{{installation}}

### Configuration
{{configuration}}

## Usage
{{usage}}

## Troubleshooting
{{troubleshooting}}

## FAQ
{{faq}}

---
*Auto-generated by Claudia Coder*
`

export const TECH_SPECS_TEMPLATE = `# {{projectName}} - Technical Specification

## Architecture Overview
{{architectureOverview}}

## Tech Stack
{{techStack}}

## Project Structure
{{projectStructure}}

## APIs
{{apis}}

## Data Models
{{dataModels}}

## Security Considerations
{{security}}

## Performance Considerations
{{performance}}

## Dependencies
{{dependencies}}

---
*Auto-generated by Claudia Coder*
`

export const REQUIREMENTS_TEMPLATE = `# {{projectName}} - Requirements Document

## Project Overview
{{overview}}

## Objectives
{{objectives}}

## Scope
### In Scope
{{inScope}}

### Out of Scope
{{outOfScope}}

## Functional Requirements
{{functionalRequirements}}

## Non-Functional Requirements
{{nonFunctionalRequirements}}

## Acceptance Criteria
{{acceptanceCriteria}}

## Assumptions
{{assumptions}}

## Risks
{{risks}}

---
*Auto-generated by Claudia Coder*
`

export type DocType = "work-summary" | "user-guide" | "tech-specs" | "requirements"

export interface DocTemplateData {
  projectName: string
  projectDescription?: string
  sessionId?: string
  startedAt?: string
  completedAt?: string
  duration?: string
  mode?: string
  packetCount?: number
  successCount?: number
  failedCount?: number
  packets?: Array<{ title: string; status: string; description: string }>
  events?: Array<{ timestamp: string; type: string; message: string }>
  qualityGates?: {
    tests: { success: boolean; output?: string }
    typeCheck: { success: boolean; output?: string }
    build: { success: boolean; output?: string }
  }
  buildPlan?: {
    objectives: string[]
    nonGoals: string[]
    assumptions: string[]
    risks: string[]
    techStack: string[]
    phases: Array<{ name: string; description: string }>
  }
  notes?: string
}

/**
 * Fill template with data
 */
export function fillTemplate(template: string, data: Record<string, string | undefined>): string {
  let result = template

  for (const [key, value] of Object.entries(data)) {
    const placeholder = new RegExp(`\\{\\{${key}\\}\\}`, "g")
    result = result.replace(placeholder, value || "N/A")
  }

  // Remove any remaining placeholders
  result = result.replace(/\{\{[^}]+\}\}/g, "N/A")

  return result
}

/**
 * Generate work summary document
 */
export function generateWorkSummary(data: DocTemplateData): string {
  const packetsTable = data.packets?.length
    ? `| Packet | Status | Description |
|--------|--------|-------------|
${data.packets.map(p => `| ${p.title} | ${p.status} | ${p.description.slice(0, 50)}... |`).join("\n")}`
    : "No packets processed."

  const activityTimeline = data.events?.length
    ? data.events.map(e => `- **${e.timestamp}** [${e.type}] ${e.message}`).join("\n")
    : "No activity recorded."

  let qualityGates = "Quality gates not available."
  if (data.qualityGates) {
    qualityGates = `
- **Tests:** ${data.qualityGates.tests.success ? "Passed" : "Failed"}
- **TypeScript:** ${data.qualityGates.typeCheck.success ? "Passed" : "Failed"}
- **Build:** ${data.qualityGates.build.success ? "Passed" : "Failed"}
`
  }

  return fillTemplate(WORK_SUMMARY_TEMPLATE, {
    projectName: data.projectName,
    sessionId: data.sessionId,
    startedAt: data.startedAt,
    completedAt: data.completedAt,
    duration: data.duration,
    mode: data.mode,
    packetCount: String(data.packetCount || 0),
    successCount: String(data.successCount || 0),
    failedCount: String(data.failedCount || 0),
    packetsTable,
    activityTimeline,
    qualityGates,
    notes: data.notes,
  })
}

/**
 * Generate AI prompt for user guide
 */
export function getUserGuidePrompt(data: DocTemplateData): string {
  return `Generate a comprehensive user guide for the following project.

Project Name: ${data.projectName}
Description: ${data.projectDescription || "N/A"}

Build Plan:
- Objectives: ${data.buildPlan?.objectives?.join(", ") || "N/A"}
- Tech Stack: ${data.buildPlan?.techStack?.join(", ") || "N/A"}
- Phases: ${data.buildPlan?.phases?.map(p => p.name).join(", ") || "N/A"}

Generate a user guide following this structure:
1. Overview - What the project does and who it's for
2. Features - Key features and capabilities
3. Getting Started - Prerequisites, installation, configuration
4. Usage - How to use the main features
5. Troubleshooting - Common issues and solutions
6. FAQ - Frequently asked questions

Write in clear, concise language. Include code examples where appropriate.
Format as markdown.`
}

/**
 * Generate AI prompt for tech specs
 */
export function getTechSpecsPrompt(data: DocTemplateData): string {
  return `Generate technical specifications for the following project.

Project Name: ${data.projectName}
Description: ${data.projectDescription || "N/A"}

Build Plan:
- Tech Stack: ${data.buildPlan?.techStack?.join(", ") || "N/A"}
- Assumptions: ${data.buildPlan?.assumptions?.join(", ") || "N/A"}

Generate technical specifications following this structure:
1. Architecture Overview - High-level system design
2. Tech Stack - Technologies used and why
3. Project Structure - Directory layout and organization
4. APIs - API endpoints and contracts
5. Data Models - Key data structures
6. Security Considerations - Security measures
7. Performance Considerations - Performance optimizations
8. Dependencies - External dependencies

Be technical and detailed. Include diagrams in mermaid format where helpful.
Format as markdown.`
}

/**
 * Generate AI prompt for requirements document
 */
export function getRequirementsPrompt(data: DocTemplateData): string {
  return `Generate a requirements document for the following project.

Project Name: ${data.projectName}
Description: ${data.projectDescription || "N/A"}

Build Plan:
- Objectives: ${data.buildPlan?.objectives?.join("; ") || "N/A"}
- Non-Goals: ${data.buildPlan?.nonGoals?.join("; ") || "N/A"}
- Assumptions: ${data.buildPlan?.assumptions?.join("; ") || "N/A"}
- Risks: ${data.buildPlan?.risks?.join("; ") || "N/A"}

Generate requirements following this structure:
1. Project Overview - Summary of the project
2. Objectives - What we're trying to achieve
3. Scope - In scope and out of scope items
4. Functional Requirements - Features and functionality
5. Non-Functional Requirements - Performance, security, etc.
6. Acceptance Criteria - How we know it's done
7. Assumptions - What we assume to be true
8. Risks - Potential risks and mitigations

Be specific and measurable. Use clear requirement language (shall, must, should).
Format as markdown.`
}
