"""
Medical Advice Disclaimer Enforcement

Ensures that all responses generated by the assistant are prefixed with a clear disclaimer
that the AI does not provide medical advice.
"""

from __future__ import annotations

DISCLAIMER_TEXT = (
    "⚠️ **Disclaimer**: This tool provides information only and does not constitute "
    "medical advice.  Please consult a licensed healthcare professional before "
    "making any health‑related decisions."
)

def prepend_disclaimer(response_text: str) -> str:
    """
    Prefix the given *response_text* with the standard disclaimer.

    Parameters
    ----------
    response_text : str
        The raw answer from the model or knowledge base.
    Returns
    -------
    str
        Disclaimer‑prefixed text ready for display.
    """
    return f"{DISCLAIMER_TEXT}\n\n{response_text}"